### ISSUE TITLE
Error Uploading Reports

### ISSUE THREAD

**Issue by joe-gall** [maciejmaciejewski/azure-pipelines-postman#17]
Receiving an error during the upload step of Azure DevOps Release Pipeline

2021-01-21T23:33:14.2221950Z ##[section]Starting: Upload Postman Html Report
2021-01-21T23:33:14.2230010Z ==============================================================================
2021-01-21T23:33:14.2230511Z Task         : Upload Postman HTML Report
2021-01-21T23:33:14.2230896Z Description  : Upload Postman HTML Report
2021-01-21T23:33:14.2231292Z Version      : 1.1.3
2021-01-21T23:33:14.2231608Z Author       : Maciej Maciejewski
2021-01-21T23:33:14.2232099Z Help         : https://github.com/maciejmaciejewski/azure-pipelines-postman#usage-examples
2021-01-21T23:33:14.2232742Z ==============================================================================
2021-01-21T23:33:16.1381315Z ##[warning]TypeError: expected a string
    at module.exports (/home/omitted/azagent/_work/_tasks/UploadPostmanHtmlReport_f5384bf0-1b5c-11ea-b0cc-5b064956a213/1.1.3/node_modules/dashify/index.js:11:38)
    at generateName (/home/omitted/azagent/_work/_tasks/UploadPostmanHtmlReport_f5384bf0-1b5c-11ea-b0cc-5b064956a213/1.1.3/index.js:49:21)
    at files.forEach.file (/home/omitted/azagent/_work/_tasks/UploadPostmanHtmlReport_f5384bf0-1b5c-11ea-b0cc-5b064956a213/1.1.3/index.js:32:13)
    at Array.forEach (<anonymous>)
    at run (/home/omitted/azagent/_work/_tasks/UploadPostmanHtmlReport_f5384bf0-1b5c-11ea-b0cc-5b064956a213/1.1.3/index.js:18:9)
    at Object.<anonymous> (/home/omitted/azagent/_work/_tasks/UploadPostmanHtmlReport_f5384bf0-1b5c-11ea-b0cc-5b064956a213/1.1.3/index.js:92:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2021-01-21T23:33:16.1500565Z ##[section]Finishing: Upload Postman Html Report

I noticed the YAML created for the step through the classic job editor omits tabName when using the default name "Postman"  Changing the  Report Tab Name name to something else does make it appear in the YAML, but the error persists.  Sample of the YAML when using the default name Postman. 

steps:
- task: MaciejMaciejewski.postman-report.UploadPostmanHtmlReport.UploadPostmanHtmlReport@1
  displayName: 'Upload Postman Html Report'
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)/newman'
  continueOnError: true
  condition: succeededOrFailed()

**Comment by aynacisevda** [comment]
We take same error during Azure DevOps Server Pipeline Integration.

**Comment by mikaelsand** [comment]
**Hi there!**
I did not have the exact same issue but perhaps this might help you:

The error is not the best. It should really read "I could not find your output file".
This happens when either the "Run Tests" cmd step does not work or when you do like I did: Point Postman publish Html Report to the wrong directory.

Here are my misconfigured steps:

- Install newman and HtmlExtra. Uses `$(System.DefaultWorkingDirectory)` as Working directory.
- Run Tests using Newman and HtmlExtra. Uses `PostmanFiles` as Working directory, as this is the name of the folder where my collectionfile was stored,  and outputs to a subfolder called "Extra".
- Upload Postman Html Report. Uses `$(System.DefaultWorkingDirectory)/Extra` <-- Wrong

I used the "Publish artifact" step to view all the files and then I realized that I needed to update the Upload Postman Html Report step to point to  the correct folder. In my case `$(System.DefaultWorkingDirectory)/PostmanFiles/Extra` <-- Correct
